version: '3.8'
services: 
  database:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdb:/var/lib/postgres/data/
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle
    ports: 
      - "3001:3000"
    depends_on:
      - database

volumes:
  pgdb:
  bundler_gems:
